export { solidityQuery } from "@/core/tree-sitter/queries/solidity";
export { default as phpQuery } from "@/core/tree-sitter/queries/php";
export { vueQuery } from "@/core/tree-sitter/queries/vue";
export { default as typescriptQuery } from "@/core/tree-sitter/queries/typescript";
export { default as tsxQuery } from "@/core/tree-sitter/queries/tsx";
export { default as pythonQuery } from "@/core/tree-sitter/queries/python";
export { default as javascriptQuery } from "@/core/tree-sitter/queries/javascript";
export { default as javaQuery } from "@/core/tree-sitter/queries/java";
export { default as rustQuery } from "@/core/tree-sitter/queries/rust";
export { default as rubyQuery } from "@/core/tree-sitter/queries/ruby";
export { default as cppQuery } from "@/core/tree-sitter/queries/cpp";
export { default as cQuery } from "@/core/tree-sitter/queries/c";
export { default as csharpQuery } from "@/core/tree-sitter/queries/c-sharp";
export { default as goQuery } from "@/core/tree-sitter/queries/go";
export { default as swiftQuery } from "@/core/tree-sitter/queries/swift";
export { default as kotlinQuery } from "@/core/tree-sitter/queries/kotlin";
export { default as cssQuery } from "@/core/tree-sitter/queries/css";
export { default as elixirQuery } from "@/core/tree-sitter/queries/elixir";
export { default as htmlQuery } from "@/core/tree-sitter/queries/html";
export { default as luaQuery } from "@/core/tree-sitter/queries/lua";
export { ocamlQuery } from "@/core/tree-sitter/queries/ocaml";
export { tomlQuery } from "@/core/tree-sitter/queries/toml";
export { default as systemrdlQuery } from "@/core/tree-sitter/queries/systemrdl";
export { default as tlaPlusQuery } from "@/core/tree-sitter/queries/tlaplus";
export { zigQuery } from "@/core/tree-sitter/queries/zig";
export { default as embeddedTemplateQuery } from "@/core/tree-sitter/queries/embedded_template";
export { elispQuery } from "@/core/tree-sitter/queries/elisp";
export { scalaQuery } from "@/core/tree-sitter/queries/scala";
